### ISSUE TITLE
How to add json array into metalsmith-collections?

### ISSUE THREAD

**Issue by surajdalvi** [metalsmith/collections#29]
I have json array with me and i want to add these array into metalsmith-collections. how i do it please help me?

**Comment by madeofpeople** [comment]
@surajdalvi you may want to look at [metalsmith-json](https://www.npmjs.com/package/metalsmith-json)

**Comment by woodyrew** [comment]
@surajdalvi Do you want the `json` as metadata of a collection or to have collections based on the `json`?

An example of the `json` and what you're expecting might be useful.

**Comment by virajsoni06** [comment]
Hey @woodyrew, I'm facing a similar problem. What I'm trying to do is have a collection based on the `json` data

I'm fairly new to Metalsmith and I'm not sure where to begin with

I have the following code in my plugins for generating files from json

`"plugins": {
  "metalsmith-markdown": {
    "smartypants": true,
    "smartLists": true,
    "gfm": true,
    "tables": true
  },
  "metalsmith-permalinks": {},
  "metalsmith-json-to-files": {
    "source_path": "./json/"
  },
  "metalsmith-collections": {
    "jsonTest": {}
  },
  "metalsmith-layouts": {
    "engine": 'handlebars',
    "directory": './templates',
    "partials": './templates/partials',
    "default": 'index.hbs'
  }
}`

And my markdown file has the following YAML matter

`---
title: Albums
layout: portfolio.hbs
json_files:
    source_file: jsonTest
    filename_pattern: portfolio/:data.slug
    as_permalink: true
    layout: single.hbs
    title: data.slug
    pageTitle: data.slug
    pageTitle2: data.title.rendered
    collection: jsonTest
---
`

The problem here is, I have a `header.hbs` partial in which I want to render the title for the single pages as well. But when I run metalsmith, it is not adding any title in the generated file

Thanks.

**Comment by woodyrew** [comment]
@virajsoni06 Do you have a repository I could look at?

**Comment by virajsoni06** [comment]
@woodyrew Sorry for the late response, but I figured it out. I added json as metadata into collections

```        
"metalsmith-collections": {
	"posts": {
		"metadata": "./json/blog.json",
		"sortBy":  "date"
	},
},
```

**Comment by woodyrew** [comment]
@lambtron This issue can be closed. (Sorry if you're not the correct person to reference). Could the repo be moved to the metalsmith org?
